/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExportViewRouteImport } from './routes/export-view'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorProjectIdRouteImport } from './routes/editor.$projectId'
import { Route as ApiGenerateReadmeRouteImport } from './routes/api/generate/readme'
import { Route as ApiGenerateArchitectureRouteImport } from './routes/api/generate/architecture'

const ExportViewRoute = ExportViewRouteImport.update({
  id: '/export-view',
  path: '/export-view',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorProjectIdRoute = EditorProjectIdRouteImport.update({
  id: '/editor/$projectId',
  path: '/editor/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateReadmeRoute = ApiGenerateReadmeRouteImport.update({
  id: '/api/generate/readme',
  path: '/api/generate/readme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateArchitectureRoute = ApiGenerateArchitectureRouteImport.update({
  id: '/api/generate/architecture',
  path: '/api/generate/architecture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/export-view': typeof ExportViewRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/api/generate/architecture': typeof ApiGenerateArchitectureRoute
  '/api/generate/readme': typeof ApiGenerateReadmeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/export-view': typeof ExportViewRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/api/generate/architecture': typeof ApiGenerateArchitectureRoute
  '/api/generate/readme': typeof ApiGenerateReadmeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/export-view': typeof ExportViewRoute
  '/editor/$projectId': typeof EditorProjectIdRoute
  '/api/generate/architecture': typeof ApiGenerateArchitectureRoute
  '/api/generate/readme': typeof ApiGenerateReadmeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/export-view'
    | '/editor/$projectId'
    | '/api/generate/architecture'
    | '/api/generate/readme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/export-view'
    | '/editor/$projectId'
    | '/api/generate/architecture'
    | '/api/generate/readme'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/export-view'
    | '/editor/$projectId'
    | '/api/generate/architecture'
    | '/api/generate/readme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ExportViewRoute: typeof ExportViewRoute
  EditorProjectIdRoute: typeof EditorProjectIdRoute
  ApiGenerateArchitectureRoute: typeof ApiGenerateArchitectureRoute
  ApiGenerateReadmeRoute: typeof ApiGenerateReadmeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/export-view': {
      id: '/export-view'
      path: '/export-view'
      fullPath: '/export-view'
      preLoaderRoute: typeof ExportViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$projectId': {
      id: '/editor/$projectId'
      path: '/editor/$projectId'
      fullPath: '/editor/$projectId'
      preLoaderRoute: typeof EditorProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/readme': {
      id: '/api/generate/readme'
      path: '/api/generate/readme'
      fullPath: '/api/generate/readme'
      preLoaderRoute: typeof ApiGenerateReadmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate/architecture': {
      id: '/api/generate/architecture'
      path: '/api/generate/architecture'
      fullPath: '/api/generate/architecture'
      preLoaderRoute: typeof ApiGenerateArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ExportViewRoute: ExportViewRoute,
  EditorProjectIdRoute: EditorProjectIdRoute,
  ApiGenerateArchitectureRoute: ApiGenerateArchitectureRoute,
  ApiGenerateReadmeRoute: ApiGenerateReadmeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
